config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  get 'pages/hello_world', as: :hello_world
  get 'pages/reaction_test', as: :reaction_test
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def hello_world
  end

  def reaction_test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReaction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/hello_world.html.erb
<h1>Pages#hello_world</h1>
<p>Find me in app/views/pages/hello_world.html.erb</p>

<%= javascript_pack_tag 'application' %>
<%= javascript_pack_tag 'hello_react' %>

app/views/pages/home.html.erb
<h1>
  Rails-Reaction
</h1>

<p>
  A workflow for Rails and
  <a href="https://github.com/artsy/reaction">Reaction</a>
</p>

<nav>
  <ul>
    <li>
      <a href="<%= hello_world_path %>">Hello, world</a>
    </li>
    <li>
      <a href="<%= reaction_test_path %>">Reaction test</a>
    </li>
  </ul>

</nav>

app/views/pages/reaction_test.html.erb
<h1>Pages#reaction_test</h1>
<p>Find me in app/views/pages/reaction_test.html.erb</p>